import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),dataFile=path.join(root,'dev-data.json');
const seed={patients:[],dentists:[{id:1,fullName:'Dr. Maya Perera',specialization:'General Dentistry',consultationFee:2500,active:true}],treatments:[{id:1,code:'CONS',name:'Consultation',cost:0,active:true},{id:2,code:'CLEAN',name:'Dental Cleaning',cost:4500,active:true},{id:3,code:'FILL',name:'Dental Filling',cost:6500,active:true},{id:4,code:'EXT',name:'Tooth Extraction',cost:8000,active:true},{id:5,code:'RCT',name:'Root Canal Treatment',cost:25000,active:true}],appointments:[],bills:[]};
let db=fs.existsSync(dataFile)?JSON.parse(fs.readFileSync(dataFile,'utf8')):seed; const save=()=>fs.writeFileSync(dataFile,JSON.stringify(db,null,2));
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'});res.end(status===204?'':JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})}),nextId=a=>Math.max(0,...a.map(x=>x.id||0))+1;
const error=(res,status,message)=>json(res,status,{timestamp:new Date().toISOString(),status,message,fieldErrors:{}}),expand=a=>({...a,patient:db.patients.find(x=>x.id===a.patientId),dentist:db.dentists.find(x=>x.id===a.dentistId),treatments:db.treatments.filter(x=>(a.treatmentIds||[]).includes(x.id))});
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost:8080'); if(req.method==='OPTIONS')return json(res,204,{});
 if(req.method==='POST'&&url.pathname==='/api/auth/login'){const x=await body(req);return x.username==='admin'&&x.password==='Admin@123'?json(res,200,{token:'local-demo-'+crypto.randomUUID(),username:'admin',fullName:'Clinic Administrator',role:'ADMIN'}):error(res,400,'Incorrect username or password.');}
 if(req.method==='POST'&&url.pathname==='/api/auth/signup'){const x=await body(req);if(!x.username||!x.password||!x.fullName||!x.role)return error(res,400,'Username, password, full name, and role are required.');return json(res,200,{token:'local-demo-'+crypto.randomUUID(),username:x.username,fullName:x.fullName,role:x.role});}
 if(!req.headers.authorization?.startsWith('Bearer '))return error(res,401,'Please sign in to continue.');
 if(req.method==='GET'&&url.pathname==='/api/patients'){const q=(url.searchParams.get('q')||'').toLowerCase();return json(res,200,db.patients.filter(x=>!q||x.fullName.toLowerCase().includes(q)||x.phone.includes(q)));}
 if(req.method==='POST'&&url.pathname==='/api/patients'){const x=await body(req);if(!x.fullName||!x.phone)return error(res,400,'Full name and phone are required.');const item={...x,id:nextId(db.patients),createdAt:new Date().toISOString()};db.patients.push(item);save();return json(res,200,item);}
 let m=url.pathname.match(/^\/api\/patients\/(\d+)$/);if(req.method==='PUT'&&m){const i=db.patients.findIndex(x=>x.id===+m[1]);if(i<0)return error(res,404,'Patient not found.');db.patients[i]={...db.patients[i],...await body(req)};save();return json(res,200,db.patients[i]);}
 for(const type of ['dentists','treatments']){if(req.method==='GET'&&url.pathname===`/api/${type}`)return json(res,200,db[type]);if(req.method==='POST'&&url.pathname===`/api/${type}`){const item={...await body(req),id:nextId(db[type]),createdAt:new Date().toISOString()};db[type].push(item);save();return json(res,200,item);}m=url.pathname.match(new RegExp(`^/api/${type}/(\\d+)$`));if(req.method==='PUT'&&m){const i=db[type].findIndex(x=>x.id===+m[1]);if(i<0)return error(res,404,'Record not found.');db[type][i]={...db[type][i],...await body(req)};save();return json(res,200,db[type][i]);}}
 if(req.method==='GET'&&url.pathname==='/api/appointments'){const all=url.searchParams.get('all')==='true',date=url.searchParams.get('date')||new Date().toISOString().slice(0,10);return json(res,200,db.appointments.filter(x=>all||x.appointmentTime.startsWith(date)).sort((a,b)=>a.appointmentTime.localeCompare(b.appointmentTime)).map(expand));}
 if(req.method==='POST'&&url.pathname==='/api/appointments'){const x=await body(req),start=new Date(x.appointmentTime),end=new Date(start.getTime()+(+x.durationMinutes||30)*60000),conflict=db.appointments.some(a=>a.dentistId===x.dentistId&&a.status!=='CANCELLED'&&start<new Date(new Date(a.appointmentTime).getTime()+a.durationMinutes*60000)&&end>new Date(a.appointmentTime));if(conflict)return error(res,409,'This dentist already has an appointment during the selected time.');const item={...x,id:nextId(db.appointments),appointmentNumber:`APT-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,status:'SCHEDULED',createdAt:new Date().toISOString()};db.appointments.push(item);save();return json(res,200,expand(item));}
 m=url.pathname.match(/^\/api\/appointments\/([^/]+)$/);if(m&&req.method==='GET'){const a=db.appointments.find(x=>x.appointmentNumber===m[1]);return a?json(res,200,expand(a)):error(res,404,`Appointment ${m[1]} was not found.`);}if(m&&req.method==='PUT'){const i=db.appointments.findIndex(x=>x.appointmentNumber===m[1]);if(i<0)return error(res,404,'Appointment not found.');db.appointments[i]={...db.appointments[i],...await body(req)};save();return json(res,200,expand(db.appointments[i]));}
 m=url.pathname.match(/^\/api\/appointments\/([^/]+)\/(cancel|complete)$/);if(m&&req.method==='PATCH'){const a=db.appointments.find(x=>x.appointmentNumber===m[1]);if(!a)return error(res,404,'Appointment not found.');a.status=m[2]==='cancel'?'CANCELLED':'COMPLETED';save();return json(res,200,expand(a));}
 m=url.pathname.match(/^\/api\/bills\/appointment\/([^/]+)$/);if(m&&req.method==='POST'){const a=db.appointments.find(x=>x.appointmentNumber===m[1]||String(x.id)===m[1]);if(!a)return error(res,404,'Appointment not found. Select an appointment from the list or enter its full appointment number.');let b=db.bills.find(x=>x.appointmentNumber===a.appointmentNumber);if(!b){const e=expand(a),tc=e.treatments.reduce((n,t)=>n+(+t.cost),0);b={id:nextId(db.bills),invoiceNumber:`INV-${Date.now()}`,appointmentNumber:a.appointmentNumber,consultationFee:+e.dentist.consultationFee,treatmentCost:tc,total:+e.dentist.consultationFee+tc,paymentStatus:'UNPAID',createdAt:new Date().toISOString()};db.bills.push(b);save();}return json(res,200,{...b,appointment:expand(a)});}
 m=url.pathname.match(/^\/api\/bills\/([^/]+)\/pay$/);if(m&&req.method==='PATCH'){const b=db.bills.find(x=>x.invoiceNumber===m[1]);if(!b)return error(res,404,'Invoice not found.');b.paymentStatus='PAID';save();return json(res,200,{...b,appointment:expand(db.appointments.find(x=>x.appointmentNumber===b.appointmentNumber))});}
 if(req.method==='GET'&&url.pathname==='/api/dashboard'){const date=new Date().toISOString().slice(0,10),daily=db.appointments.filter(x=>x.appointmentTime.startsWith(date));return json(res,200,{date,appointmentsToday:daily.length,scheduled:daily.filter(x=>x.status==='SCHEDULED').length,completed:daily.filter(x=>x.status==='COMPLETED').length,patients:db.patients.length,dentists:db.dentists.length,paidRevenue:db.bills.filter(x=>x.paymentStatus==='PAID').reduce((n,x)=>n+x.total,0),upcoming:daily.filter(x=>new Date(x.appointmentTime)>new Date()).map(expand).slice(0,5)});}
 return error(res,404,'API route not found.');}catch(e){console.error(e);return error(res,500,'The local API encountered an error.');}});
server.listen(8080,'127.0.0.1',()=>console.log('Sunrise local development API: http://127.0.0.1:8080'));
