import{useState}from'react';
import{api,money}from'../api';
import{Alert,Status}from'./UI';

export default function AppointmentLookup(){
 const[number,setNumber]=useState(''),[appointment,setAppointment]=useState(),[error,setError]=useState();
 async function search(e){e.preventDefault();setError();setAppointment();try{setAppointment(await api(`/appointments/${number.trim()}`))}catch(x){setError(x)}}
 return <div className="card panel appointment-lookup"><div className="panel-title"><div><h2>Display appointment details</h2><p>Search using the complete appointment number.</p></div></div><form className="search appointment-search" onSubmit={search}><i className="bi bi-search"/><input value={number} onChange={e=>setNumber(e.target.value.toUpperCase())} placeholder="Example: APT-20260816-887312" required/><button className="btn btn-primary">Search</button></form><Alert error={error}/>{appointment&&<div className="appointment-details"><div className="details-heading"><div><small>APPOINTMENT NUMBER</small><h3>{appointment.appointmentNumber}</h3></div><Status value={appointment.status}/></div><div className="details-grid"><div><small>Patient</small><strong>{appointment.patient.fullName}</strong><span>Patient ID #{appointment.patient.id}</span></div><div><small>Phone</small><strong>{appointment.patient.phone}</strong><span>{appointment.patient.email||'No email recorded'}</span></div><div><small>Date and time</small><strong>{new Date(appointment.appointmentTime).toLocaleString()}</strong><span>{appointment.durationMinutes} minutes</span></div><div><small>Dentist</small><strong>{appointment.dentist.fullName}</strong><span>{appointment.dentist.specialization}</span></div><div><small>Patient details</small><strong>{appointment.patient.dateOfBirth||'Date of birth not recorded'}</strong><span>{appointment.patient.gender||'Gender not recorded'} · {appointment.patient.address||'No address'}</span></div><div><small>Medical notes</small><strong>{appointment.patient.medicalNotes||'None recorded'}</strong><span>Appointment note: {appointment.notes||'None'}</span></div></div><div className="details-treatments"><small>TREATMENTS</small>{appointment.treatments?.length?appointment.treatments.map(t=><span key={t.id}>{t.name} <strong>{money(t.cost)}</strong></span>):<span>No treatments selected</span>}</div></div>}</div>
}
