import{useState}from'react';
import{api}from'../api';
import{Alert,Field}from'./UI';

const blank={fullName:'',phone:'',dateOfBirth:'',gender:'',email:'',address:'',medicalNotes:''};

export default function PatientPicker({patients,value,onChange,onCreated}){
 const[adding,setAdding]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState();
 async function create(){setError();if(!form.fullName.trim()||!form.phone.trim()){setError('Full name and phone are required.');return}try{const patient=await api('/patients',{method:'POST',body:JSON.stringify({...form,dateOfBirth:form.dateOfBirth||null})});onCreated(patient);onChange(String(patient.id));setForm(blank);setAdding(false)}catch(x){setError(x)}}
 return <div className="patient-picker"><Field label="Patient" required><div className="picker-row"><select className="form-select" value={value} onChange={e=>onChange(e.target.value)} required><option value="">Select existing patient</option>{patients.map(p=><option value={p.id} key={p.id}>{p.fullName} — {p.phone}</option>)}</select><button type="button" className="btn btn-outline-primary text-nowrap" onClick={()=>setAdding(true)}><i className="bi bi-person-plus"/> New patient</button></div></Field>{adding&&<div className="quick-patient"><div className="quick-patient-head"><strong>Register new patient</strong><button type="button" onClick={()=>setAdding(false)}>×</button></div><Alert error={error}/><div className="form-grid"><Field label="Full name" required><input className="form-control" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Phone" required><input className="form-control" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Date of birth"><input type="date" className="form-control" value={form.dateOfBirth} onChange={e=>setForm({...form,dateOfBirth:e.target.value})}/></Field><Field label="Gender"><select className="form-select" value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></Field></div><div className="quick-patient-actions"><button type="button" className="btn btn-light" onClick={()=>setAdding(false)}>Cancel</button><button type="button" className="btn btn-primary" onClick={create}>Register and select</button></div></div>}</div>
}
