import{useEffect,useState}from'react';
import{api,money}from'../api';
import{Alert,Page,Status}from'../components/UI';

export default function Billing(){
 const[number,setNumber]=useState(''),[appointments,setAppointments]=useState([]),[bill,setBill]=useState(),[error,setError]=useState();
 useEffect(()=>{api('/appointments?all=true').then(setAppointments).catch(setError)},[]);
 async function generate(e){e.preventDefault();setError();setBill();try{setBill(await api(`/bills/appointment/${number.trim()}`,{method:'POST'}))}catch(x){setError(x)}}
 async function pay(){setBill(await api(`/bills/${bill.invoiceNumber}/pay`,{method:'PATCH'}))}
 function receiptDocument(){
  const receipt=document.getElementById('receipt')?.cloneNode(true);if(!receipt)return '';
  receipt.querySelector('.receipt-actions')?.remove();
  return `<!doctype html><html><head><meta charset="utf-8"><title>Receipt ${bill.invoiceNumber}</title><style>body{font-family:Arial,sans-serif;color:#18313a;margin:0;padding:32px}.receipt{max-width:720px;margin:auto}.receipt-brand{display:flex;gap:12px;align-items:center}.receipt-brand h2{margin:0}.receipt-meta{display:grid;grid-template-columns:1fr 1fr auto;gap:20px;margin:25px 0}.receipt-meta strong,.receipt-patient strong{display:block}.receipt-patient{display:flex;flex-direction:column;margin:20px 0}.line,.total{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #ddd}.total{font-size:20px;font-weight:bold;border-top:2px solid #18313a}.status{padding:5px 10px;border-radius:20px;background:#e4f5eb;color:#2f7950;font-size:11px}@page{margin:14mm}</style></head><body>${receipt.outerHTML}</body></html>`;
 }
 function printReceipt(){const html=receiptDocument(),win=window.open('','_blank','width=820,height=900');if(!win){downloadReceipt();return}win.document.open();win.document.write(html);win.document.close();setTimeout(()=>{win.focus();win.print()},500)}
 function downloadReceipt(){const blob=new Blob([receiptDocument()],{type:'text/html'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${bill.invoiceNumber}-receipt.html`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <Page title="Billing & receipts" subtitle="Select an appointment, calculate its fees, and issue a clear receipt."><div className="billing-grid"><div className="card panel"><h2>Choose appointment</h2><form className="mt-3" onSubmit={generate}><select className="form-select mb-3" value={number} onChange={e=>setNumber(e.target.value)} required><option value="">Select a patient and appointment</option>{appointments.map(a=><option value={a.appointmentNumber} key={a.id}>{a.appointmentNumber} — {a.patient.fullName} — {new Date(a.appointmentTime).toLocaleString()}</option>)}</select><div className="d-flex gap-2"><input className="form-control" value={number} onChange={e=>setNumber(e.target.value.toUpperCase())} placeholder="Appointment number or ID"/><button className="btn btn-primary text-nowrap">Create bill</button></div></form><Alert error={error}/>{!appointments.length&&!error&&<p className="text-muted mt-3">No appointments are available for billing yet.</p>}<p className="text-muted mt-3 mb-0">The total includes the dentist's consultation fee and all treatments selected on the appointment.</p></div>{bill&&<div className="receipt card" id="receipt"><div className="receipt-brand"><i className="bi bi-brightness-high-fill"/><div><h2>Sunrise Dental Clinic</h2><span>Payment receipt</span></div></div><div className="receipt-meta"><div><small>Invoice</small><strong>{bill.invoiceNumber}</strong></div><div><small>Date</small><strong>{new Date(bill.createdAt).toLocaleDateString()}</strong></div><Status value={bill.paymentStatus}/></div><hr/><div className="receipt-patient"><small>BILLED TO</small><strong>{bill.appointment.patient.fullName}</strong><span>{bill.appointment.appointmentNumber} · {bill.appointment.dentist.fullName}</span></div><div className="line"><span>Consultation fee</span><strong>{money(bill.consultationFee)}</strong></div>{bill.appointment.treatments.map(t=><div className="line" key={t.id}><span>{t.name}</span><strong>{money(t.cost)}</strong></div>)}<div className="total"><span>Total</span><strong>{money(bill.total)}</strong></div><div className="receipt-actions">{bill.paymentStatus==='UNPAID'&&<button className="btn btn-success" onClick={pay}><i className="bi bi-check2-circle"/> Mark paid</button>}<button className="btn btn-outline-secondary" onClick={printReceipt}><i className="bi bi-printer"/> Print receipt</button><button className="btn btn-outline-secondary" onClick={downloadReceipt}><i className="bi bi-download"/> Save receipt</button></div></div>}</div></Page>
}
